---
site: workflowr::wflow_site
title: "Home"
output:
  workflowr::wflow_html:
    toc: false
---

This repo is my "catch-all" for putting things in that may relate to various ongoing projects.


# Ash

* [Null simulations with larger n=13500](ash_pi0_largern.html)
* [NPMLE with larger n=100000](ash_npmle_big.html)
* [Examine the delta operator for ash](ash_delta_operator.html)
* [Ash on poisson data](ash_pois_bcell.html)


# Mr Ash

* [implementing mr ash as a penalized method](mr_ash_pen.html)
* [coordinate ascent and parallel version](mr_ash_sca.html)
* [mr.ash.alpha applied to changepoint problems](mr.ash.changepoint.html)
* [combining mr.ash and ridge regression/iterative ridge regression](mr.ash_ridge.html)
* [bimodal example from "Bayesian lasso"" paper](blasso_bimodal_example.html)
* [mr ash vs lasso: example where lasso does better](mr_ash_vs_lasso.html)
* [mr ash vs lasso: follow-up checking objective fn](mr_ash_vs_lasso_02.html)
* [lasso vs ridge: follow-up checking p=1000 vs p=2000](lasso_vs_ridge.html)
* [Debugging and scaling](mr.ash.debug.html)

# Ridge Regression

* [Ridge regression for trend filtering](ridge_trend_filter.html)
* [Ridge regression via conjugate gradient](ridge_conjugate_gradient.html)
* [EM for hyperparameters Ridge regression](ridge_em.html)
* [EM for hyperparameters of Ridge regression using SVD](ridge_em_svd.html)
* [EM for hyperparameters of Ridge regression - convergence issue](ridge.hyperparam.convergence.html)

* [ADMM for ridge regression with heterogenous prior variances](ridge_admm.html)

* [Sloppy ADMM](sloppy_admm.html)

# Lasso

* [Fit lasso by EM](lasso_em.html)
* [teach myself ADMM (L1 and L0)](admm_01.html)
* [check scaling of glmnet with n](lasso_complexity.html)

# EBMR

* [An initially suprising overfitting result for EB lasso](eblasso.suprising.html)
* [An illustration of ebmr with estimated grid](ebmr_illustration.html)


# Mash

* [Initial mash analysis of RBC z scores](rbc_zscore_mash.html)
* [Comparing the UDI BFs from mash with originals](cov_udi_explore.html)


# Mouthwash

* [Looking at how Mouthwash deals with t distributions vs normal](vicar_t.html)


# Flash

* [Illustration of conservative behaviour issue](flash_r1vsr0_conservative.html)

* [Looking at differentiating the likelihood at the null](EBflash_1d.html)

* [Apply SSVD to GTEX data](ssvd_gtex.html)

* [Method of moments for EbayesThresh ](ebayes.mm.html)

* [flashier run on stocks data](flashier_stocks.html)
* [Notes on a sparse PCA objective function](spca_objective1.html)

* [Notes on the log1p transform for count/Poisson data](flashier_log1p.html)

* [Approximating Poisson likelihood by normal, with log1p transform](poisson_log1p.html)


* [Initial runs of flashier on text data](flashier_sla_text.html)
* [Flashier semi-NMF on text data](flashier_sla_point_Laplace.html)
* [Try at using shifted exponential prior in flashier (did not work as I expected)](flashier_nmf_shifted_prior.html)

# NMF

* [Try NMF on a simple simulation with sparse factors](nmf_sparse.html)
* [Run NMF on covariance matrices, including tree-like case](nmf_simple_examples.html)
* [Non-negative matrix underapproximation via EM](nmu_em.html)
* [A power method for fitting symmetric NMF](power_nneg.html)
* [An EB version of the power method for symmetric NMF](ebpower.html)

# ICA

* [Initial try of fastICA on simulated data](fastica_01.html)
* [Single unit fastICA on simulated data](fastica_02.html)
* [Single unit fastICA with centering, to help find asymmetric binary groups](fastica_centered.html)
* [Motivated by ICA, I try a flash+low-rank approach](flash_pca.html)

# Multinomial factor models

* [Possible version of structure/admixture with sparsity via ARD-like prior](sparse_structure.html)

# Weighted SVD 

* [Outline of EM algorithm for fitting weighted SVD](wSVD.html)
* [Investigation of weighted SVD for Poisson data](plra.html)
* [Brief experiment with primePCA](primepca.html)
* [Example of convergence problem in softimpute](softimpute_convergence_problem.html)

# Finemapping

* [Comparison of varbvs and varbvsmix](FMO2.html)
* [A simple approach to fine mapping](simple_mapping.html)
* [A new VB approach](newVB.html)
* [Connect new VB to single SNP Bayesian analysis](newVB.ss.html)
* [selective inference on toy example](selective_inference_toy.html)
* [selective inference with correlated variables](selective_inference.html)
* [hierarchical inference example](hierinf_toyexample.html)


# Logistic regression

* [Logistic regression z scores decrease as effect size increases](logistic_z_scores.html)


# LD score regression

* [An initial look at XtX (Sigma)^{-1}](ldsr_01.html)

# Missing Data in regression

* [Pseudo-data idea](mr_missing_data.html)
* [Approximate Inference with missing data](mr_missing_data2.html)

# Approximate message passing and related

* [Compare precision and covariance for ridge regression](prec_vs_cov.html)
* [Initial try of VAMP](vamp_01.html)

# Depletion

* [Using ash for depletion](ash-depletion.html)

# Single cell data

* [explore t test on log-transformed data](simple_transform_simulation.html)
* [initial play with sinkhorn normalization](sinkhorn.html)
* [flashier on pbmc_purified data](flashier_pbmc_purified.html)


# flash-drift

* [look at SVD applied to tree structured data](tree_pca.html)
* [Eigen-decomposition applied to some simple 4- and 8-tip trees](tree_pca_02.html)
* [Apply sparsepca and flash to some tree data](tree_pca_03.html)
* [Look at effect of size of first factor on flash](flash_f1_size.html)
* [Flash-cov on overlapping groups](flash_cov_overlapping_groups.html)
* [A look at estimates of the latent factors on trees](tree_ebcd.html)
* [Outline of a method for building trees topdown using flash](flash_tree.html)
* [Some results for trees and overlapping groups, initializing using point-laplace](flashier_point_laplace_initialization.html)

# EBNM
* [A bimodal mixture of 2 normals ebnm function](ebnm_binormal.html)

# IRLS

* [implementation of irls for logistic regression](irls.html)

[rmarkdown]: http://rmarkdown.rstudio.com/rmarkdown_websites.htm
[rstudio]: https://www.rstudio.com/products/rstudio/download/preview/
